# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwin_cb.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QHBoxLayout, QHeaderView,
    QLabel, QMainWindow, QMenu, QMenuBar,
    QScrollArea, QSizePolicy, QSlider, QSpacerItem,
    QSplitter, QStatusBar, QToolButton, QTreeView,
    QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1837, 1286)
        self.new_proj_action = QAction(MainWindow)
        self.new_proj_action.setObjectName(u"new_proj_action")
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.AppointmentNew))
        self.new_proj_action.setIcon(icon)
        self.open_proj_action = QAction(MainWindow)
        self.open_proj_action.setObjectName(u"open_proj_action")
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentOpen))
        self.open_proj_action.setIcon(icon1)
        self.save_action = QAction(MainWindow)
        self.save_action.setObjectName(u"save_action")
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentSave))
        self.save_action.setIcon(icon2)
        self.save_as_action = QAction(MainWindow)
        self.save_as_action.setObjectName(u"save_as_action")
        icon3 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentSaveAs))
        self.save_as_action.setIcon(icon3)
        self.export_to_datapack_action = QAction(MainWindow)
        self.export_to_datapack_action.setObjectName(u"export_to_datapack_action")
        icon4 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.FolderNew))
        self.export_to_datapack_action.setIcon(icon4)
        self.exit_action = QAction(MainWindow)
        self.exit_action.setObjectName(u"exit_action")
        icon5 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ApplicationExit))
        self.exit_action.setIcon(icon5)
        self.undo_action = QAction(MainWindow)
        self.undo_action.setObjectName(u"undo_action")
        self.undo_action.setEnabled(False)
        icon6 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditUndo))
        self.undo_action.setIcon(icon6)
        self.redo_action = QAction(MainWindow)
        self.redo_action.setObjectName(u"redo_action")
        self.redo_action.setEnabled(False)
        icon7 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditRedo))
        self.redo_action.setIcon(icon7)
        self.copy_element_action = QAction(MainWindow)
        self.copy_element_action.setObjectName(u"copy_element_action")
        self.copy_element_action.setEnabled(False)
        icon8 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditCopy))
        self.copy_element_action.setIcon(icon8)
        self.delete_element_action = QAction(MainWindow)
        self.delete_element_action.setObjectName(u"delete_element_action")
        self.delete_element_action.setEnabled(False)
        icon9 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ListRemove))
        self.delete_element_action.setIcon(icon9)
        self.pos_selector_action = QAction(MainWindow)
        self.pos_selector_action.setObjectName(u"pos_selector_action")
        self.element_list_action_toggle = QAction(MainWindow)
        self.element_list_action_toggle.setObjectName(u"element_list_action_toggle")
        self.element_list_action_toggle.setCheckable(True)
        self.element_list_action_toggle.setChecked(True)
        self.property_panel_action_toggle = QAction(MainWindow)
        self.property_panel_action_toggle.setObjectName(u"property_panel_action_toggle")
        self.property_panel_action_toggle.setCheckable(True)
        self.property_panel_action_toggle.setChecked(True)
        self.inspector_action_toggle = QAction(MainWindow)
        self.inspector_action_toggle.setObjectName(u"inspector_action_toggle")
        self.inspector_action_toggle.setCheckable(True)
        self.inspector_action_toggle.setChecked(True)
        self.timeline_action_toggle = QAction(MainWindow)
        self.timeline_action_toggle.setObjectName(u"timeline_action_toggle")
        self.timeline_action_toggle.setCheckable(True)
        self.timeline_action_toggle.setChecked(True)
        self.proj_settings_action = QAction(MainWindow)
        self.proj_settings_action.setObjectName(u"proj_settings_action")
        icon10 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentProperties))
        self.proj_settings_action.setIcon(icon10)
        self.about_DynFirework_action = QAction(MainWindow)
        self.about_DynFirework_action.setObjectName(u"about_DynFirework_action")
        self.about_DynFirework_action.setEnabled(True)
        icon11 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.HelpAbout))
        self.about_DynFirework_action.setIcon(icon11)
        self.help_action = QAction(MainWindow)
        self.help_action.setObjectName(u"help_action")
        icon12 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditFind))
        self.help_action.setIcon(icon12)
        self.play_action = QAction(MainWindow)
        self.play_action.setObjectName(u"play_action")
        self.play_action.setEnabled(False)
        icon13 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MediaPlaybackStart))
        self.play_action.setIcon(icon13)
        self.stop_action = QAction(MainWindow)
        self.stop_action.setObjectName(u"stop_action")
        self.stop_action.setEnabled(False)
        icon14 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MediaPlaybackStop))
        self.stop_action.setIcon(icon14)
        self.backward_action = QAction(MainWindow)
        self.backward_action.setObjectName(u"backward_action")
        self.backward_action.setEnabled(False)
        icon15 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MediaSkipBackward))
        self.backward_action.setIcon(icon15)
        self.hint_tick_toggle_action = QAction(MainWindow)
        self.hint_tick_toggle_action.setObjectName(u"hint_tick_toggle_action")
        self.hint_tick_toggle_action.setCheckable(True)
        self.hint_tick_toggle_action.setChecked(True)
        self.time_tick_toggle_action = QAction(MainWindow)
        self.time_tick_toggle_action.setObjectName(u"time_tick_toggle_action")
        self.time_tick_toggle_action.setCheckable(True)
        self.time_tick_toggle_action.setChecked(True)
        self.pause_action = QAction(MainWindow)
        self.pause_action.setObjectName(u"pause_action")
        self.pause_action.setEnabled(False)
        icon16 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.MediaPlaybackPause))
        self.pause_action.setIcon(icon16)
        self.pos_selector_3d_action = QAction(MainWindow)
        self.pos_selector_3d_action.setObjectName(u"pos_selector_3d_action")
        self.pos_selector_3d_action.setEnabled(False)
        self.palette_action = QAction(MainWindow)
        self.palette_action.setObjectName(u"palette_action")
        self.palette_action.setEnabled(False)
        self.import_points_action = QAction(MainWindow)
        self.import_points_action.setObjectName(u"import_points_action")
        self.import_points_action.setEnabled(False)
        self.export_points_action = QAction(MainWindow)
        self.export_points_action.setObjectName(u"export_points_action")
        self.new_traj_action = QAction(MainWindow)
        self.new_traj_action.setObjectName(u"new_traj_action")
        self.new_firework_action = QAction(MainWindow)
        self.new_firework_action.setObjectName(u"new_firework_action")
        self.new_complex_action = QAction(MainWindow)
        self.new_complex_action.setObjectName(u"new_complex_action")
        self.new_effect_action = QAction(MainWindow)
        self.new_effect_action.setObjectName(u"new_effect_action")
        self.import_point_action = QAction(MainWindow)
        self.import_point_action.setObjectName(u"import_point_action")
        self.import_music_action = QAction(MainWindow)
        self.import_music_action.setObjectName(u"import_music_action")
        self.export_point_action = QAction(MainWindow)
        self.export_point_action.setObjectName(u"export_point_action")
        self.export_music_action = QAction(MainWindow)
        self.export_music_action.setObjectName(u"export_music_action")
        self.export_datapack_action = QAction(MainWindow)
        self.export_datapack_action.setObjectName(u"export_datapack_action")
        self.export_datapack_action.setIcon(icon4)
        self.new_tf_action = QAction(MainWindow)
        self.new_tf_action.setObjectName(u"new_tf_action")
        self.metronome_action_toggle = QAction(MainWindow)
        self.metronome_action_toggle.setObjectName(u"metronome_action_toggle")
        self.metronome_action_toggle.setCheckable(True)
        self.metronome_action_toggle.setEnabled(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_2 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.splitter_2 = QSplitter(self.centralwidget)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setStyleSheet(u"")
        self.splitter_2.setOrientation(Qt.Orientation.Vertical)
        self.splitter_2.setHandleWidth(10)
        self.upper_widget = QWidget(self.splitter_2)
        self.upper_widget.setObjectName(u"upper_widget")
        self.verticalLayout = QVBoxLayout(self.upper_widget)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.label = QLabel(self.upper_widget)
        self.label.setObjectName(u"label")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QFont()
        font.setFamilies([u"Ark Pixel 12px P zh_cn"])
        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.verticalLayout.addWidget(self.label)

        self.upper_widget_no_text = QWidget(self.upper_widget)
        self.upper_widget_no_text.setObjectName(u"upper_widget_no_text")
        self.horizontalLayout_2 = QHBoxLayout(self.upper_widget_no_text)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.splitter = QSplitter(self.upper_widget_no_text)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.splitter.setHandleWidth(10)
        self.element_list_frame = QFrame(self.splitter)
        self.element_list_frame.setObjectName(u"element_list_frame")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.element_list_frame.sizePolicy().hasHeightForWidth())
        self.element_list_frame.setSizePolicy(sizePolicy1)
        self.element_list_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.element_list_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_7 = QVBoxLayout(self.element_list_frame)
        self.verticalLayout_7.setObjectName(u"verticalLayout_7")
        self.element_list_label = QLabel(self.element_list_frame)
        self.element_list_label.setObjectName(u"element_list_label")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.element_list_label.sizePolicy().hasHeightForWidth())
        self.element_list_label.setSizePolicy(sizePolicy2)
        self.element_list_label.setFont(font)

        self.verticalLayout_7.addWidget(self.element_list_label)

        self.element_list_tree_view = QTreeView(self.element_list_frame)
        self.element_list_tree_view.setObjectName(u"element_list_tree_view")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.element_list_tree_view.sizePolicy().hasHeightForWidth())
        self.element_list_tree_view.setSizePolicy(sizePolicy3)
        self.element_list_tree_view.setFont(font)
        self.element_list_tree_view.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)

        self.verticalLayout_7.addWidget(self.element_list_tree_view)

        self.splitter.addWidget(self.element_list_frame)
        self.property_panel_area = QScrollArea(self.splitter)
        self.property_panel_area.setObjectName(u"property_panel_area")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy4.setHorizontalStretch(1)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.property_panel_area.sizePolicy().hasHeightForWidth())
        self.property_panel_area.setSizePolicy(sizePolicy4)
        self.property_panel_area.setFrameShape(QFrame.Shape.NoFrame)
        self.property_panel_area.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.property_panel_area.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 1402, 784))
        self.property_panel_area.setWidget(self.scrollAreaWidgetContents)
        self.splitter.addWidget(self.property_panel_area)
        self.inspector_frame = QFrame(self.splitter)
        self.inspector_frame.setObjectName(u"inspector_frame")
        sizePolicy1.setHeightForWidth(self.inspector_frame.sizePolicy().hasHeightForWidth())
        self.inspector_frame.setSizePolicy(sizePolicy1)
        self.inspector_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.inspector_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_3 = QVBoxLayout(self.inspector_frame)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.widget = QWidget(self.inspector_frame)
        self.widget.setObjectName(u"widget")
        sizePolicy2.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy2)
        self.widget.setFont(font)
        self.horizontalLayout_3 = QHBoxLayout(self.widget)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.inspector_label = QLabel(self.widget)
        self.inspector_label.setObjectName(u"inspector_label")
        sizePolicy3.setHeightForWidth(self.inspector_label.sizePolicy().hasHeightForWidth())
        self.inspector_label.setSizePolicy(sizePolicy3)

        self.horizontalLayout_3.addWidget(self.inspector_label)

        self.inspector_target = QLabel(self.widget)
        self.inspector_target.setObjectName(u"inspector_target")
        sizePolicy1.setHeightForWidth(self.inspector_target.sizePolicy().hasHeightForWidth())
        self.inspector_target.setSizePolicy(sizePolicy1)

        self.horizontalLayout_3.addWidget(self.inspector_target)


        self.verticalLayout_3.addWidget(self.widget)

        self.inspector = QWidget(self.inspector_frame)
        self.inspector.setObjectName(u"inspector")

        self.verticalLayout_3.addWidget(self.inspector)

        self.splitter.addWidget(self.inspector_frame)

        self.horizontalLayout_2.addWidget(self.splitter)


        self.verticalLayout.addWidget(self.upper_widget_no_text)

        self.splitter_2.addWidget(self.upper_widget)
        self.lower_frame = QFrame(self.splitter_2)
        self.lower_frame.setObjectName(u"lower_frame")
        self.lower_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.lower_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout_6 = QVBoxLayout(self.lower_frame)
        self.verticalLayout_6.setObjectName(u"verticalLayout_6")
        self.timeline_transport_bar = QWidget(self.lower_frame)
        self.timeline_transport_bar.setObjectName(u"timeline_transport_bar")
        sizePolicy3.setHeightForWidth(self.timeline_transport_bar.sizePolicy().hasHeightForWidth())
        self.timeline_transport_bar.setSizePolicy(sizePolicy3)
        self.horizontalLayout = QHBoxLayout(self.timeline_transport_bar)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.timeline_play_pause = QToolButton(self.timeline_transport_bar)
        self.timeline_play_pause.setObjectName(u"timeline_play_pause")
        sizePolicy3.setHeightForWidth(self.timeline_play_pause.sizePolicy().hasHeightForWidth())
        self.timeline_play_pause.setSizePolicy(sizePolicy3)
        font1 = QFont()
        font1.setFamilies([u"Ubuntu"])
        self.timeline_play_pause.setFont(font1)

        self.horizontalLayout.addWidget(self.timeline_play_pause)

        self.timeline_stop = QToolButton(self.timeline_transport_bar)
        self.timeline_stop.setObjectName(u"timeline_stop")
        sizePolicy3.setHeightForWidth(self.timeline_stop.sizePolicy().hasHeightForWidth())
        self.timeline_stop.setSizePolicy(sizePolicy3)

        self.horizontalLayout.addWidget(self.timeline_stop)

        self.timeline_replay = QToolButton(self.timeline_transport_bar)
        self.timeline_replay.setObjectName(u"timeline_replay")
        sizePolicy3.setHeightForWidth(self.timeline_replay.sizePolicy().hasHeightForWidth())
        self.timeline_replay.setSizePolicy(sizePolicy3)

        self.horizontalLayout.addWidget(self.timeline_replay)

        self.timeline_toggle_hint_tick = QToolButton(self.timeline_transport_bar)
        self.timeline_toggle_hint_tick.setObjectName(u"timeline_toggle_hint_tick")
        sizePolicy3.setHeightForWidth(self.timeline_toggle_hint_tick.sizePolicy().hasHeightForWidth())
        self.timeline_toggle_hint_tick.setSizePolicy(sizePolicy3)
        self.timeline_toggle_hint_tick.setCheckable(True)
        self.timeline_toggle_hint_tick.setChecked(True)

        self.horizontalLayout.addWidget(self.timeline_toggle_hint_tick)

        self.timeline_toggle_time_tick = QToolButton(self.timeline_transport_bar)
        self.timeline_toggle_time_tick.setObjectName(u"timeline_toggle_time_tick")
        sizePolicy3.setHeightForWidth(self.timeline_toggle_time_tick.sizePolicy().hasHeightForWidth())
        self.timeline_toggle_time_tick.setSizePolicy(sizePolicy3)
        self.timeline_toggle_time_tick.setCheckable(True)
        self.timeline_toggle_time_tick.setChecked(True)

        self.horizontalLayout.addWidget(self.timeline_toggle_time_tick)

        self.timeline_metronome_toggle = QToolButton(self.timeline_transport_bar)
        self.timeline_metronome_toggle.setObjectName(u"timeline_metronome_toggle")
        self.timeline_metronome_toggle.setEnabled(False)
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.timeline_metronome_toggle.sizePolicy().hasHeightForWidth())
        self.timeline_metronome_toggle.setSizePolicy(sizePolicy5)
        self.timeline_metronome_toggle.setMinimumSize(QSize(0, 0))
        self.timeline_metronome_toggle.setCheckable(True)
        self.timeline_metronome_toggle.setChecked(False)

        self.horizontalLayout.addWidget(self.timeline_metronome_toggle)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer)

        self.timeline_time = QLabel(self.timeline_transport_bar)
        self.timeline_time.setObjectName(u"timeline_time")
        sizePolicy3.setHeightForWidth(self.timeline_time.sizePolicy().hasHeightForWidth())
        self.timeline_time.setSizePolicy(sizePolicy3)
        font2 = QFont()
        font2.setFamilies([u"Monocraft Nerd Font"])
        font2.setPointSize(14)
        self.timeline_time.setFont(font2)

        self.horizontalLayout.addWidget(self.timeline_time)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_2)

        self.timeline_tick = QLabel(self.timeline_transport_bar)
        self.timeline_tick.setObjectName(u"timeline_tick")
        font3 = QFont()
        font3.setFamilies([u"Monocraft Nerd Font"])
        self.timeline_tick.setFont(font3)

        self.horizontalLayout.addWidget(self.timeline_tick)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.horizontalSpacer_3)

        self.timeline_volume = QLabel(self.timeline_transport_bar)
        self.timeline_volume.setObjectName(u"timeline_volume")
        self.timeline_volume.setFont(font)

        self.horizontalLayout.addWidget(self.timeline_volume)

        self.timeline_volume_adjust = QSlider(self.timeline_transport_bar)
        self.timeline_volume_adjust.setObjectName(u"timeline_volume_adjust")
        sizePolicy3.setHeightForWidth(self.timeline_volume_adjust.sizePolicy().hasHeightForWidth())
        self.timeline_volume_adjust.setSizePolicy(sizePolicy3)
        self.timeline_volume_adjust.setValue(75)
        self.timeline_volume_adjust.setOrientation(Qt.Orientation.Horizontal)

        self.horizontalLayout.addWidget(self.timeline_volume_adjust)

        self.timeline_horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout.addItem(self.timeline_horizontalSpacer)

        self.timeline_music_name = QLabel(self.timeline_transport_bar)
        self.timeline_music_name.setObjectName(u"timeline_music_name")
        self.timeline_music_name.setFont(font)
        self.timeline_music_name.setStyleSheet(u"color: rgb(154, 153, 150);")

        self.horizontalLayout.addWidget(self.timeline_music_name)

        self.timeline_bpm = QLabel(self.timeline_transport_bar)
        self.timeline_bpm.setObjectName(u"timeline_bpm")
        self.timeline_bpm.setFont(font3)

        self.horizontalLayout.addWidget(self.timeline_bpm)


        self.verticalLayout_6.addWidget(self.timeline_transport_bar)

        self.timeline_area = QScrollArea(self.lower_frame)
        self.timeline_area.setObjectName(u"timeline_area")
        self.timeline_area.setWidgetResizable(True)
        self.scrollAreaWidgetContents_4 = QWidget()
        self.scrollAreaWidgetContents_4.setObjectName(u"scrollAreaWidgetContents_4")
        self.scrollAreaWidgetContents_4.setGeometry(QRect(0, 0, 1797, 318))
        self.timeline_area.setWidget(self.scrollAreaWidgetContents_4)

        self.verticalLayout_6.addWidget(self.timeline_area)

        self.splitter_2.addWidget(self.lower_frame)

        self.verticalLayout_2.addWidget(self.splitter_2)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1837, 31))
        self.menubar.setFont(font)
        self.file_menu = QMenu(self.menubar)
        self.file_menu.setObjectName(u"file_menu")
        self.file_menu.setFont(font)
        self.import_menu = QMenu(self.file_menu)
        self.import_menu.setObjectName(u"import_menu")
        self.import_menu.setFont(font)
        self.export_menu = QMenu(self.file_menu)
        self.export_menu.setObjectName(u"export_menu")
        self.export_menu.setFont(font)
        self.edit_menu = QMenu(self.menubar)
        self.edit_menu.setObjectName(u"edit_menu")
        self.edit_menu.setFont(font)
        self.new_element_menu = QMenu(self.edit_menu)
        self.new_element_menu.setObjectName(u"new_element_menu")
        self.new_element_menu.setFont(font)
        self.view_menu = QMenu(self.menubar)
        self.view_menu.setObjectName(u"view_menu")
        self.view_menu.setFont(font)
        self.proj_menu = QMenu(self.menubar)
        self.proj_menu.setObjectName(u"proj_menu")
        self.proj_menu.setFont(font)
        self.about_menu = QMenu(self.menubar)
        self.about_menu.setObjectName(u"about_menu")
        self.about_menu.setFont(font)
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.file_menu.menuAction())
        self.menubar.addAction(self.edit_menu.menuAction())
        self.menubar.addAction(self.view_menu.menuAction())
        self.menubar.addAction(self.proj_menu.menuAction())
        self.menubar.addAction(self.about_menu.menuAction())
        self.file_menu.addAction(self.new_proj_action)
        self.file_menu.addAction(self.open_proj_action)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.save_action)
        self.file_menu.addAction(self.save_as_action)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.import_menu.menuAction())
        self.file_menu.addAction(self.export_menu.menuAction())
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.exit_action)
        self.import_menu.addAction(self.import_music_action)
        self.import_menu.addAction(self.import_point_action)
        self.export_menu.addAction(self.export_datapack_action)
        self.export_menu.addAction(self.export_music_action)
        self.export_menu.addAction(self.export_point_action)
        self.edit_menu.addAction(self.new_element_menu.menuAction())
        self.edit_menu.addSeparator()
        self.edit_menu.addAction(self.undo_action)
        self.edit_menu.addAction(self.redo_action)
        self.edit_menu.addSeparator()
        self.edit_menu.addAction(self.copy_element_action)
        self.edit_menu.addAction(self.delete_element_action)
        self.edit_menu.addSeparator()
        self.edit_menu.addAction(self.play_action)
        self.edit_menu.addAction(self.pause_action)
        self.edit_menu.addAction(self.stop_action)
        self.edit_menu.addAction(self.backward_action)
        self.edit_menu.addSeparator()
        self.edit_menu.addAction(self.hint_tick_toggle_action)
        self.edit_menu.addAction(self.time_tick_toggle_action)
        self.new_element_menu.addAction(self.new_firework_action)
        self.new_element_menu.addAction(self.new_traj_action)
        self.new_element_menu.addAction(self.new_tf_action)
        self.view_menu.addAction(self.pos_selector_action)
        self.view_menu.addAction(self.pos_selector_3d_action)
        self.view_menu.addAction(self.palette_action)
        self.view_menu.addSeparator()
        self.view_menu.addAction(self.element_list_action_toggle)
        self.view_menu.addAction(self.property_panel_action_toggle)
        self.view_menu.addAction(self.inspector_action_toggle)
        self.view_menu.addAction(self.timeline_action_toggle)
        self.view_menu.addAction(self.metronome_action_toggle)
        self.proj_menu.addAction(self.proj_settings_action)
        self.about_menu.addAction(self.help_action)
        self.about_menu.addAction(self.about_DynFirework_action)

        self.retranslateUi(MainWindow)
        self.timeline_action_toggle.checkableChanged.connect(self.lower_frame.setVisible)
        self.exit_action.triggered.connect(MainWindow.close)
        self.element_list_action_toggle.checkableChanged.connect(self.element_list_frame.setVisible)
        self.inspector_action_toggle.checkableChanged.connect(self.inspector_frame.setVisible)
        self.property_panel_action_toggle.checkableChanged.connect(self.property_panel_area.setVisible)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.new_proj_action.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u9879\u76ee", None))
#if QT_CONFIG(shortcut)
        self.new_proj_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.open_proj_action.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u9879\u76ee", None))
#if QT_CONFIG(shortcut)
        self.open_proj_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.save_action.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
#if QT_CONFIG(shortcut)
        self.save_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.save_as_action.setText(QCoreApplication.translate("MainWindow", u"\u53e6\u5b58\u4e3a", None))
#if QT_CONFIG(shortcut)
        self.save_as_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.export_to_datapack_action.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa\u6570\u636e\u5305", None))
        self.exit_action.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
        self.undo_action.setText(QCoreApplication.translate("MainWindow", u"\u64a4\u9500", None))
#if QT_CONFIG(shortcut)
        self.undo_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.redo_action.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u505a", None))
#if QT_CONFIG(shortcut)
        self.redo_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+Z", None))
#endif // QT_CONFIG(shortcut)
        self.copy_element_action.setText(QCoreApplication.translate("MainWindow", u"\u590d\u5236\u5143\u7d20", None))
#if QT_CONFIG(shortcut)
        self.copy_element_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.delete_element_action.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664\u5143\u7d20", None))
#if QT_CONFIG(shortcut)
        self.delete_element_action.setShortcut(QCoreApplication.translate("MainWindow", u"Del", None))
#endif // QT_CONFIG(shortcut)
        self.pos_selector_action.setText(QCoreApplication.translate("MainWindow", u"\u4f4d\u7f6e\u9009\u62e9\u5668", None))
        self.element_list_action_toggle.setText(QCoreApplication.translate("MainWindow", u"\u5143\u7d20\u5217\u8868", None))
        self.property_panel_action_toggle.setText(QCoreApplication.translate("MainWindow", u"\u5c5e\u6027\u9762\u677f", None))
        self.inspector_action_toggle.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u67e5\u5668", None))
        self.timeline_action_toggle.setText(QCoreApplication.translate("MainWindow", u"\u65f6\u95f4\u7ebf", None))
        self.proj_settings_action.setText(QCoreApplication.translate("MainWindow", u"\u9879\u76ee\u8bbe\u7f6e", None))
        self.about_DynFirework_action.setText(QCoreApplication.translate("MainWindow", u"\u5173\u4e8e DynFirework", None))
        self.help_action.setText(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
#if QT_CONFIG(shortcut)
        self.help_action.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.play_action.setText(QCoreApplication.translate("MainWindow", u"\u64ad\u653e", None))
#if QT_CONFIG(shortcut)
        self.play_action.setShortcut(QCoreApplication.translate("MainWindow", u"Space", None))
#endif // QT_CONFIG(shortcut)
        self.stop_action.setText(QCoreApplication.translate("MainWindow", u"\u505c\u6b62", None))
        self.backward_action.setText(QCoreApplication.translate("MainWindow", u"\u8df3\u8f6c\u5230\u5f00\u5934", None))
        self.hint_tick_toggle_action.setText(QCoreApplication.translate("MainWindow", u"\u8f85\u52a9\u523b\u5ea6", None))
        self.time_tick_toggle_action.setText(QCoreApplication.translate("MainWindow", u"\u65f6\u95f4\u523b\u5ea6", None))
        self.pause_action.setText(QCoreApplication.translate("MainWindow", u"\u6682\u505c", None))
#if QT_CONFIG(shortcut)
        self.pause_action.setShortcut(QCoreApplication.translate("MainWindow", u"Space", None))
#endif // QT_CONFIG(shortcut)
        self.pos_selector_3d_action.setText(QCoreApplication.translate("MainWindow", u"\u7acb\u4f53\u4f4d\u7f6e\u9009\u62e9\u5668", None))
        self.palette_action.setText(QCoreApplication.translate("MainWindow", u"\u8c03\u8272\u76d8", None))
        self.import_points_action.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u5165\u70b9\u96c6", None))
        self.export_points_action.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa\u70b9\u96c6", None))
        self.new_traj_action.setText(QCoreApplication.translate("MainWindow", u"\u8f68\u8ff9", None))
        self.new_firework_action.setText(QCoreApplication.translate("MainWindow", u"\u70df\u82b1", None))
        self.new_complex_action.setText(QCoreApplication.translate("MainWindow", u"\u590d\u5408\u5143\u7d20", None))
        self.new_effect_action.setText(QCoreApplication.translate("MainWindow", u"\u6548\u679c", None))
        self.import_point_action.setText(QCoreApplication.translate("MainWindow", u"\u70b9\u96c6", None))
        self.import_music_action.setText(QCoreApplication.translate("MainWindow", u"\u97f3\u4e50", None))
        self.export_point_action.setText(QCoreApplication.translate("MainWindow", u"\u70b9\u96c6", None))
        self.export_music_action.setText(QCoreApplication.translate("MainWindow", u"\u97f3\u4e50", None))
        self.export_datapack_action.setText(QCoreApplication.translate("MainWindow", u"\u6570\u636e\u5305", None))
#if QT_CONFIG(shortcut)
        self.export_datapack_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.new_tf_action.setText(QCoreApplication.translate("MainWindow", u"\u590d\u5408\u5143\u7d20", None))
        self.metronome_action_toggle.setText(QCoreApplication.translate("MainWindow", u"\u8282\u62cd\u5668\uff08\u6d4b\u8bd5\uff09", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"<PROJECT_NAME> - <MC_VERSION>", None))
        self.element_list_label.setText(QCoreApplication.translate("MainWindow", u"\u5143\u7d20\u5217\u8868", None))
        self.inspector_label.setText(QCoreApplication.translate("MainWindow", u"\u68c0\u67e5\u5668\uff1a", None))
        self.inspector_target.setText("")
#if QT_CONFIG(tooltip)
        self.timeline_play_pause.setToolTip(QCoreApplication.translate("MainWindow", u"\u64ad\u653e/\u6682\u505c", None))
#endif // QT_CONFIG(tooltip)
        self.timeline_play_pause.setText(QCoreApplication.translate("MainWindow", u"\u25b6", None))
#if QT_CONFIG(tooltip)
        self.timeline_stop.setToolTip(QCoreApplication.translate("MainWindow", u"\u505c\u6b62", None))
#endif // QT_CONFIG(tooltip)
        self.timeline_stop.setText(QCoreApplication.translate("MainWindow", u"\u25a0", None))
#if QT_CONFIG(tooltip)
        self.timeline_replay.setToolTip(QCoreApplication.translate("MainWindow", u"\u8df3\u8f6c\u5230\u5f00\u5934", None))
#endif // QT_CONFIG(tooltip)
        self.timeline_replay.setText(QCoreApplication.translate("MainWindow", u"\U000f0459", None))
#if QT_CONFIG(tooltip)
        self.timeline_toggle_hint_tick.setToolTip(QCoreApplication.translate("MainWindow", u"\u663e\u793a/\u9690\u85cfBPM\u8f85\u52a9\u7ebf", None))
#endif // QT_CONFIG(tooltip)
        self.timeline_toggle_hint_tick.setText(QCoreApplication.translate("MainWindow", u"\u266e", None))
#if QT_CONFIG(tooltip)
        self.timeline_toggle_time_tick.setToolTip(QCoreApplication.translate("MainWindow", u"\u663e\u793a/\u9690\u85cf\u65f6\u95f4\u523b\u5ea6\u7ebf", None))
#endif // QT_CONFIG(tooltip)
        self.timeline_toggle_time_tick.setText(QCoreApplication.translate("MainWindow", u"\uf017", None))
#if QT_CONFIG(tooltip)
        self.timeline_metronome_toggle.setToolTip(QCoreApplication.translate("MainWindow", u"\u8282\u62cd\u5668\uff08\u6d4b\u8bd5\uff09", None))
#endif // QT_CONFIG(tooltip)
        self.timeline_metronome_toggle.setText(QCoreApplication.translate("MainWindow", u"\u266c", None))
        self.timeline_time.setText(QCoreApplication.translate("MainWindow", u"00:00", None))
        self.timeline_tick.setText(QCoreApplication.translate("MainWindow", u"Tick: 0", None))
        self.timeline_volume.setText(QCoreApplication.translate("MainWindow", u"\u97f3\u91cf", None))
        self.timeline_music_name.setText("")
        self.timeline_bpm.setText(QCoreApplication.translate("MainWindow", u"BPM: 120", None))
        self.file_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6", None))
        self.import_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u5bfc\u5165...", None))
        self.export_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa...", None))
        self.edit_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u7f16\u8f91", None))
        self.new_element_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u6dfb\u52a0\u5143\u7d20...", None))
        self.view_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u89c6\u56fe", None))
        self.proj_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u9879\u76ee", None))
        self.about_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u5173\u4e8e", None))
    # retranslateUi

