# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'pos_selector.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtOpenGLWidgets import QOpenGLWidget
from PySide6.QtWidgets import (QAbstractButton, QApplication, QDialogButtonBox, QFrame,
    QGridLayout, QHBoxLayout, QLabel, QListView,
    QMainWindow, QMenu, QMenuBar, QSizePolicy,
    QSplitter, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1524, 1189)
        self.import_action = QAction(MainWindow)
        self.import_action.setObjectName(u"import_action")
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentOpen))
        self.import_action.setIcon(icon)
        self.export_action = QAction(MainWindow)
        self.export_action.setObjectName(u"export_action")
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentSaveAs))
        self.export_action.setIcon(icon1)
        self.exit_action = QAction(MainWindow)
        self.exit_action.setObjectName(u"exit_action")
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ApplicationExit))
        self.exit_action.setIcon(icon2)
        self.delete_action = QAction(MainWindow)
        self.delete_action.setObjectName(u"delete_action")
        icon3 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ListRemove))
        self.delete_action.setIcon(icon3)
        self.undo_action = QAction(MainWindow)
        self.undo_action.setObjectName(u"undo_action")
        icon4 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditUndo))
        self.undo_action.setIcon(icon4)
        self.redo_action = QAction(MainWindow)
        self.redo_action.setObjectName(u"redo_action")
        icon5 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditRedo))
        self.redo_action.setIcon(icon5)
        self.zoom_out_action = QAction(MainWindow)
        self.zoom_out_action.setObjectName(u"zoom_out_action")
        icon6 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ZoomOut))
        self.zoom_out_action.setIcon(icon6)
        self.zoom_in_action = QAction(MainWindow)
        self.zoom_in_action.setObjectName(u"zoom_in_action")
        icon7 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ZoomIn))
        self.zoom_in_action.setIcon(icon7)
        self.proper_size_action = QAction(MainWindow)
        self.proper_size_action.setObjectName(u"proper_size_action")
        icon8 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ZoomFitBest))
        self.proper_size_action.setIcon(icon8)
        self.grid_select_toggle = QAction(MainWindow)
        self.grid_select_toggle.setObjectName(u"grid_select_toggle")
        self.grid_select_toggle.setCheckable(True)
        self.grid_select_toggle.setChecked(True)
        self.radar_graph_toggle = QAction(MainWindow)
        self.radar_graph_toggle.setObjectName(u"radar_graph_toggle")
        self.radar_graph_toggle.setCheckable(True)
        self.move_center_action = QAction(MainWindow)
        self.move_center_action.setObjectName(u"move_center_action")
        self.back_to_zero_action = QAction(MainWindow)
        self.back_to_zero_action.setObjectName(u"back_to_zero_action")
        icon9 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ProcessStop))
        self.back_to_zero_action.setIcon(icon9)
        self.actionY = QAction(MainWindow)
        self.actionY.setObjectName(u"actionY")
        self.actionX_axis = QAction(MainWindow)
        self.actionX_axis.setObjectName(u"actionX_axis")
        self.actionX_axis.setCheckable(True)
        self.actionX_axis.setChecked(False)
        self.actionY_axis = QAction(MainWindow)
        self.actionY_axis.setObjectName(u"actionY_axis")
        self.actionY_axis.setCheckable(True)
        self.actionZ_axis = QAction(MainWindow)
        self.actionZ_axis.setObjectName(u"actionZ_axis")
        self.actionZ_axis.setCheckable(True)
        self.actionXp_Yp_Zp = QAction(MainWindow)
        self.actionXp_Yp_Zp.setObjectName(u"actionXp_Yp_Zp")
        self.actionXp_Yp_Zn = QAction(MainWindow)
        self.actionXp_Yp_Zn.setObjectName(u"actionXp_Yp_Zn")
        self.actionXp_Yn_Zn = QAction(MainWindow)
        self.actionXp_Yn_Zn.setObjectName(u"actionXp_Yn_Zn")
        self.actionXn_Yn_Zn = QAction(MainWindow)
        self.actionXn_Yn_Zn.setObjectName(u"actionXn_Yn_Zn")
        self.actionXp_Yn_Zp = QAction(MainWindow)
        self.actionXp_Yn_Zp.setObjectName(u"actionXp_Yn_Zp")
        self.actionXn_Yp_Zp = QAction(MainWindow)
        self.actionXn_Yp_Zp.setObjectName(u"actionXn_Yp_Zp")
        self.actionXn_Yn_Zp = QAction(MainWindow)
        self.actionXn_Yn_Zp.setObjectName(u"actionXn_Yn_Zp")
        self.actionXn_Yp_Zn = QAction(MainWindow)
        self.actionXn_Yp_Zn.setObjectName(u"actionXn_Yp_Zn")
        self.action_add_point = QAction(MainWindow)
        self.action_add_point.setObjectName(u"action_add_point")
        font = QFont()
        font.setFamilies([u"Ark Pixel 12px P zh_cn"])
        self.action_add_point.setFont(font)
        self.action_add_line = QAction(MainWindow)
        self.action_add_line.setObjectName(u"action_add_line")
        self.action = QAction(MainWindow)
        self.action.setObjectName(u"action")
        self.action_3 = QAction(MainWindow)
        self.action_3.setObjectName(u"action_3")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.horizontalLayout_2 = QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.splitter = QSplitter(self.frame)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.splitter.setHandleWidth(10)
        self.openGLWidget = QOpenGLWidget(self.splitter)
        self.openGLWidget.setObjectName(u"openGLWidget")
        self.openGLWidget.setMinimumSize(QSize(1200, 1080))
        self.splitter.addWidget(self.openGLWidget)
        self.inspector_frame = QFrame(self.splitter)
        self.inspector_frame.setObjectName(u"inspector_frame")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inspector_frame.sizePolicy().hasHeightForWidth())
        self.inspector_frame.setSizePolicy(sizePolicy)
        self.inspector_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.inspector_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout = QVBoxLayout(self.inspector_frame)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.splitter_2 = QSplitter(self.inspector_frame)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setOrientation(Qt.Orientation.Vertical)
        self.splitter_2.setHandleWidth(10)
        self.listView_points = QListView(self.splitter_2)
        self.listView_points.setObjectName(u"listView_points")
        self.splitter_2.addWidget(self.listView_points)
        self.listView_lines = QListView(self.splitter_2)
        self.listView_lines.setObjectName(u"listView_lines")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.listView_lines.sizePolicy().hasHeightForWidth())
        self.listView_lines.setSizePolicy(sizePolicy1)
        self.listView_lines.setMinimumSize(QSize(200, 0))
        font1 = QFont()
        font1.setFamilies([u"Ark Pixel 12px P ja"])
        self.listView_lines.setFont(font1)
        self.splitter_2.addWidget(self.listView_lines)

        self.verticalLayout.addWidget(self.splitter_2)

        self.text_preview_widget = QWidget(self.inspector_frame)
        self.text_preview_widget.setObjectName(u"text_preview_widget")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.text_preview_widget.sizePolicy().hasHeightForWidth())
        self.text_preview_widget.setSizePolicy(sizePolicy2)
        self.horizontalLayout = QHBoxLayout(self.text_preview_widget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.selected_point = QLabel(self.text_preview_widget)
        self.selected_point.setObjectName(u"selected_point")
        self.selected_point.setFont(font)

        self.horizontalLayout.addWidget(self.selected_point)

        self.selected_point_text = QLabel(self.text_preview_widget)
        self.selected_point_text.setObjectName(u"selected_point_text")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.selected_point_text.sizePolicy().hasHeightForWidth())
        self.selected_point_text.setSizePolicy(sizePolicy3)
        self.selected_point_text.setFont(font)
        self.selected_point_text.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout.addWidget(self.selected_point_text)


        self.verticalLayout.addWidget(self.text_preview_widget)

        self.splitter.addWidget(self.inspector_frame)

        self.horizontalLayout_2.addWidget(self.splitter)


        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.buttonBox = QDialogButtonBox(self.centralwidget)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setFont(font)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)

        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1524, 31))
        self.menubar.setFont(font)
        self.selection_menu = QMenu(self.menubar)
        self.selection_menu.setObjectName(u"selection_menu")
        self.selection_menu.setFont(font)
        self.edit_menu = QMenu(self.menubar)
        self.edit_menu.setObjectName(u"edit_menu")
        self.edit_menu.setFont(font)
        self.new_menu = QMenu(self.edit_menu)
        self.new_menu.setObjectName(u"new_menu")
        self.new_menu.setFont(font)
        self.view_menu = QMenu(self.menubar)
        self.view_menu.setObjectName(u"view_menu")
        self.view_menu.setFont(font)
        self.axial_view_menu = QMenu(self.view_menu)
        self.axial_view_menu.setObjectName(u"axial_view_menu")
        self.axial_view_menu.setFont(font)
        self.ortho_view_menu = QMenu(self.view_menu)
        self.ortho_view_menu.setObjectName(u"ortho_view_menu")
        self.ortho_view_menu.setFont(font)
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.selection_menu.menuAction())
        self.menubar.addAction(self.edit_menu.menuAction())
        self.menubar.addAction(self.view_menu.menuAction())
        self.selection_menu.addAction(self.import_action)
        self.selection_menu.addAction(self.export_action)
        self.selection_menu.addSeparator()
        self.selection_menu.addAction(self.exit_action)
        self.edit_menu.addAction(self.new_menu.menuAction())
        self.edit_menu.addAction(self.delete_action)
        self.edit_menu.addSeparator()
        self.edit_menu.addAction(self.undo_action)
        self.edit_menu.addAction(self.redo_action)
        self.edit_menu.addSeparator()
        self.edit_menu.addAction(self.action)
        self.edit_menu.addAction(self.action_3)
        self.edit_menu.addSeparator()
        self.edit_menu.addAction(self.move_center_action)
        self.new_menu.addAction(self.action_add_point)
        self.new_menu.addAction(self.action_add_line)
        self.view_menu.addAction(self.zoom_out_action)
        self.view_menu.addAction(self.zoom_in_action)
        self.view_menu.addAction(self.proper_size_action)
        self.view_menu.addSeparator()
        self.view_menu.addAction(self.back_to_zero_action)
        self.view_menu.addAction(self.axial_view_menu.menuAction())
        self.view_menu.addAction(self.ortho_view_menu.menuAction())
        self.axial_view_menu.addAction(self.actionX_axis)
        self.axial_view_menu.addAction(self.actionY_axis)
        self.axial_view_menu.addAction(self.actionZ_axis)
        self.ortho_view_menu.addAction(self.actionXp_Yp_Zp)
        self.ortho_view_menu.addAction(self.actionXp_Yp_Zn)
        self.ortho_view_menu.addAction(self.actionXp_Yn_Zp)
        self.ortho_view_menu.addAction(self.actionXp_Yn_Zn)
        self.ortho_view_menu.addAction(self.actionXn_Yp_Zp)
        self.ortho_view_menu.addAction(self.actionXn_Yp_Zn)
        self.ortho_view_menu.addAction(self.actionXn_Yn_Zp)
        self.ortho_view_menu.addAction(self.actionXn_Yn_Zn)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.import_action.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u5165", None))
        self.export_action.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa", None))
        self.exit_action.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
        self.delete_action.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
        self.undo_action.setText(QCoreApplication.translate("MainWindow", u"\u64a4\u9500", None))
        self.redo_action.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u505a", None))
        self.zoom_out_action.setText(QCoreApplication.translate("MainWindow", u"\u7f29\u5c0f", None))
        self.zoom_in_action.setText(QCoreApplication.translate("MainWindow", u"\u653e\u5927", None))
        self.proper_size_action.setText(QCoreApplication.translate("MainWindow", u"\u5408\u9002\u5927\u5c0f", None))
        self.grid_select_toggle.setText(QCoreApplication.translate("MainWindow", u"\u7f51\u683c\u56fe", None))
        self.radar_graph_toggle.setText(QCoreApplication.translate("MainWindow", u"\u96f7\u8fbe\u56fe", None))
        self.move_center_action.setText(QCoreApplication.translate("MainWindow", u"\u79fb\u52a8\u4e2d\u5fc3...", None))
        self.back_to_zero_action.setText(QCoreApplication.translate("MainWindow", u"\u56de\u5230\u539f\u70b9", None))
        self.actionY.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.actionX_axis.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.actionY_axis.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.actionZ_axis.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.actionXp_Yp_Zp.setText(QCoreApplication.translate("MainWindow", u"X+/Y+/Z+", None))
        self.actionXp_Yp_Zn.setText(QCoreApplication.translate("MainWindow", u"X+/Y+/Z-", None))
        self.actionXp_Yn_Zn.setText(QCoreApplication.translate("MainWindow", u"X+/Y-/Z-", None))
        self.actionXn_Yn_Zn.setText(QCoreApplication.translate("MainWindow", u"X-/Y-/Z-", None))
        self.actionXp_Yn_Zp.setText(QCoreApplication.translate("MainWindow", u"X+/Y-/Z+", None))
        self.actionXn_Yp_Zp.setText(QCoreApplication.translate("MainWindow", u"X-/Y+/Z+", None))
        self.actionXn_Yn_Zp.setText(QCoreApplication.translate("MainWindow", u"X-/Y-/Z+", None))
        self.actionXn_Yp_Zn.setText(QCoreApplication.translate("MainWindow", u"X-/Y+/Z-", None))
        self.action_add_point.setText(QCoreApplication.translate("MainWindow", u"\u4f4d\u7f6e\u70b9", None))
        self.action_add_line.setText(QCoreApplication.translate("MainWindow", u"\u8f85\u52a9\u7ebf", None))
        self.action.setText(QCoreApplication.translate("MainWindow", u"\u9690\u85cf", None))
        self.action_3.setText(QCoreApplication.translate("MainWindow", u"\u663e\u793a", None))
        self.selected_point.setText(QCoreApplication.translate("MainWindow", u"\u5df2\u9009\u62e9\uff1a", None))
        self.selected_point_text.setText(QCoreApplication.translate("MainWindow", u"<\u70b9>", None))
        self.selection_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u9009\u9879", None))
        self.edit_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u7f16\u8f91", None))
        self.new_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u65b0\u589e", None))
        self.view_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u89c6\u56fe", None))
        self.axial_view_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u8f74\u5411\u89c6\u56fe", None))
        self.ortho_view_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u6b63\u4ea4\u89c6\u56fe", None))
    # retranslateUi

