# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'pos_selector.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QDialogButtonBox, QFrame,
    QGridLayout, QHBoxLayout, QLabel, QListView,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QSplitter, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(831, 631)
        self.import_action = QAction(MainWindow)
        self.import_action.setObjectName(u"import_action")
        icon = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentOpen))
        self.import_action.setIcon(icon)
        self.export_action = QAction(MainWindow)
        self.export_action.setObjectName(u"export_action")
        icon1 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.DocumentSaveAs))
        self.export_action.setIcon(icon1)
        self.exit_action = QAction(MainWindow)
        self.exit_action.setObjectName(u"exit_action")
        icon2 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ApplicationExit))
        self.exit_action.setIcon(icon2)
        self.add_action = QAction(MainWindow)
        self.add_action.setObjectName(u"add_action")
        icon3 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ListAdd))
        self.add_action.setIcon(icon3)
        self.delete_action = QAction(MainWindow)
        self.delete_action.setObjectName(u"delete_action")
        self.delete_action.setEnabled(False)
        icon4 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ListRemove))
        self.delete_action.setIcon(icon4)
        self.undo_action = QAction(MainWindow)
        self.undo_action.setObjectName(u"undo_action")
        self.undo_action.setEnabled(False)
        icon5 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditUndo))
        self.undo_action.setIcon(icon5)
        self.redo_action = QAction(MainWindow)
        self.redo_action.setObjectName(u"redo_action")
        self.redo_action.setEnabled(False)
        icon6 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.EditRedo))
        self.redo_action.setIcon(icon6)
        self.min_size_action = QAction(MainWindow)
        self.min_size_action.setObjectName(u"min_size_action")
        icon7 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ZoomOut))
        self.min_size_action.setIcon(icon7)
        self.max_size_action = QAction(MainWindow)
        self.max_size_action.setObjectName(u"max_size_action")
        icon8 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ZoomIn))
        self.max_size_action.setIcon(icon8)
        self.proper_size_action = QAction(MainWindow)
        self.proper_size_action.setObjectName(u"proper_size_action")
        icon9 = QIcon(QIcon.fromTheme(QIcon.ThemeIcon.ZoomFitBest))
        self.proper_size_action.setIcon(icon9)
        self.grid_select_toggle = QAction(MainWindow)
        self.grid_select_toggle.setObjectName(u"grid_select_toggle")
        self.grid_select_toggle.setCheckable(True)
        self.grid_select_toggle.setChecked(True)
        self.radar_graph_toggle = QAction(MainWindow)
        self.radar_graph_toggle.setObjectName(u"radar_graph_toggle")
        self.radar_graph_toggle.setCheckable(True)
        self.move_center_action = QAction(MainWindow)
        self.move_center_action.setObjectName(u"move_center_action")
        self.move_center_action.setEnabled(False)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout = QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.frame = QFrame(self.centralwidget)
        self.frame.setObjectName(u"frame")
        self.frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout_2 = QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.splitter = QSplitter(self.frame)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Orientation.Horizontal)
        self.map_frame = QFrame(self.splitter)
        self.map_frame.setObjectName(u"map_frame")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.map_frame.sizePolicy().hasHeightForWidth())
        self.map_frame.setSizePolicy(sizePolicy)
        self.map_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.map_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout_3 = QGridLayout(self.map_frame)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.widget = QWidget(self.map_frame)
        self.widget.setObjectName(u"widget")
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QSize(500, 500))

        self.gridLayout_3.addWidget(self.widget, 0, 0, 1, 1)

        self.splitter.addWidget(self.map_frame)
        self.inspector_frame = QFrame(self.splitter)
        self.inspector_frame.setObjectName(u"inspector_frame")
        self.inspector_frame.setFrameShape(QFrame.Shape.StyledPanel)
        self.inspector_frame.setFrameShadow(QFrame.Shadow.Raised)
        self.gridLayout_4 = QGridLayout(self.inspector_frame)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.edit_and_delete_widget = QWidget(self.inspector_frame)
        self.edit_and_delete_widget.setObjectName(u"edit_and_delete_widget")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.edit_and_delete_widget.sizePolicy().hasHeightForWidth())
        self.edit_and_delete_widget.setSizePolicy(sizePolicy1)
        self.horizontalLayout_3 = QHBoxLayout(self.edit_and_delete_widget)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.edit_point_button = QPushButton(self.edit_and_delete_widget)
        self.edit_point_button.setObjectName(u"edit_point_button")
        self.edit_point_button.setEnabled(False)
        font = QFont()
        font.setFamilies([u"Ark Pixel 12px P zh_cn"])
        self.edit_point_button.setFont(font)

        self.horizontalLayout_3.addWidget(self.edit_point_button)

        self.delete_point_button = QPushButton(self.edit_and_delete_widget)
        self.delete_point_button.setObjectName(u"delete_point_button")
        self.delete_point_button.setEnabled(False)
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.delete_point_button.sizePolicy().hasHeightForWidth())
        self.delete_point_button.setSizePolicy(sizePolicy2)
        self.delete_point_button.setFont(font)

        self.horizontalLayout_3.addWidget(self.delete_point_button)


        self.gridLayout_4.addWidget(self.edit_and_delete_widget, 2, 0, 1, 1)

        self.listView_element = QListView(self.inspector_frame)
        self.listView_element.setObjectName(u"listView_element")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.listView_element.sizePolicy().hasHeightForWidth())
        self.listView_element.setSizePolicy(sizePolicy3)
        self.listView_element.setMinimumSize(QSize(200, 0))

        self.gridLayout_4.addWidget(self.listView_element, 0, 0, 2, 1)

        self.text_preview_widget = QWidget(self.inspector_frame)
        self.text_preview_widget.setObjectName(u"text_preview_widget")
        sizePolicy1.setHeightForWidth(self.text_preview_widget.sizePolicy().hasHeightForWidth())
        self.text_preview_widget.setSizePolicy(sizePolicy1)
        self.horizontalLayout = QHBoxLayout(self.text_preview_widget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.selected_point = QLabel(self.text_preview_widget)
        self.selected_point.setObjectName(u"selected_point")
        self.selected_point.setFont(font)

        self.horizontalLayout.addWidget(self.selected_point)

        self.selected_point_text = QLabel(self.text_preview_widget)
        self.selected_point_text.setObjectName(u"selected_point_text")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Preferred)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.selected_point_text.sizePolicy().hasHeightForWidth())
        self.selected_point_text.setSizePolicy(sizePolicy4)
        self.selected_point_text.setFont(font)
        self.selected_point_text.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout.addWidget(self.selected_point_text)


        self.gridLayout_4.addWidget(self.text_preview_widget, 3, 0, 1, 1)

        self.splitter.addWidget(self.inspector_frame)

        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)


        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)

        self.buttonBox = QDialogButtonBox(self.centralwidget)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setFont(font)
        self.buttonBox.setStandardButtons(QDialogButtonBox.StandardButton.Cancel|QDialogButtonBox.StandardButton.Ok)

        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 831, 31))
        self.menubar.setFont(font)
        self.selection_menu = QMenu(self.menubar)
        self.selection_menu.setObjectName(u"selection_menu")
        self.selection_menu.setFont(font)
        self.edit_menu = QMenu(self.menubar)
        self.edit_menu.setObjectName(u"edit_menu")
        self.edit_menu.setFont(font)
        self.view_menu = QMenu(self.menubar)
        self.view_menu.setObjectName(u"view_menu")
        self.view_menu.setFont(font)
        MainWindow.setMenuBar(self.menubar)

        self.menubar.addAction(self.selection_menu.menuAction())
        self.menubar.addAction(self.edit_menu.menuAction())
        self.menubar.addAction(self.view_menu.menuAction())
        self.selection_menu.addAction(self.import_action)
        self.selection_menu.addAction(self.export_action)
        self.selection_menu.addSeparator()
        self.selection_menu.addAction(self.exit_action)
        self.edit_menu.addAction(self.add_action)
        self.edit_menu.addAction(self.delete_action)
        self.edit_menu.addSeparator()
        self.edit_menu.addAction(self.undo_action)
        self.edit_menu.addAction(self.redo_action)
        self.edit_menu.addSeparator()
        self.edit_menu.addAction(self.move_center_action)
        self.view_menu.addAction(self.min_size_action)
        self.view_menu.addAction(self.max_size_action)
        self.view_menu.addAction(self.proper_size_action)
        self.view_menu.addSeparator()
        self.view_menu.addAction(self.grid_select_toggle)
        self.view_menu.addAction(self.radar_graph_toggle)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.import_action.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u5165", None))
#if QT_CONFIG(shortcut)
        self.import_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.export_action.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa", None))
#if QT_CONFIG(shortcut)
        self.export_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.exit_action.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa", None))
        self.add_action.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u589e", None))
#if QT_CONFIG(shortcut)
        self.add_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.delete_action.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
        self.undo_action.setText(QCoreApplication.translate("MainWindow", u"\u64a4\u9500", None))
#if QT_CONFIG(shortcut)
        self.undo_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.redo_action.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u505a", None))
#if QT_CONFIG(shortcut)
        self.redo_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+Z", None))
#endif // QT_CONFIG(shortcut)
        self.min_size_action.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5c0f", None))
#if QT_CONFIG(shortcut)
        self.min_size_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+-", None))
#endif // QT_CONFIG(shortcut)
        self.max_size_action.setText(QCoreApplication.translate("MainWindow", u"\u6700\u5927", None))
#if QT_CONFIG(shortcut)
        self.max_size_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+=", None))
#endif // QT_CONFIG(shortcut)
        self.proper_size_action.setText(QCoreApplication.translate("MainWindow", u"\u5408\u9002\u5927\u5c0f", None))
#if QT_CONFIG(shortcut)
        self.proper_size_action.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+0", None))
#endif // QT_CONFIG(shortcut)
        self.grid_select_toggle.setText(QCoreApplication.translate("MainWindow", u"\u7f51\u683c\u56fe", None))
        self.radar_graph_toggle.setText(QCoreApplication.translate("MainWindow", u"\u96f7\u8fbe\u56fe", None))
        self.move_center_action.setText(QCoreApplication.translate("MainWindow", u"\u79fb\u52a8\u4e2d\u5fc3", None))
        self.edit_point_button.setText(QCoreApplication.translate("MainWindow", u"\u7f16\u8f91", None))
        self.delete_point_button.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
#if QT_CONFIG(shortcut)
        self.delete_point_button.setShortcut(QCoreApplication.translate("MainWindow", u"Del", None))
#endif // QT_CONFIG(shortcut)
        self.selected_point.setText(QCoreApplication.translate("MainWindow", u"\u5df2\u9009\u62e9\uff1a", None))
        self.selected_point_text.setText(QCoreApplication.translate("MainWindow", u"<\u70b9>", None))
        self.selection_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u9009\u9879", None))
        self.edit_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u7f16\u8f91", None))
        self.view_menu.setTitle(QCoreApplication.translate("MainWindow", u"\u89c6\u56fe", None))
    # retranslateUi

